In [53]:
import numpy as np

np1=np.array([[2,3,3],[4,5,4]])
np2=np.array([2,4,3,4])

print("---np1---")
print(np1)
print("---np2---")
print(np2)

print("----維度----")
print(np1.ndim) #維度
print("----形狀----")
print(np1.shape) #形狀
print("----資料型別----")
print(np1.dtype) #資料型別

print(np2.dtype)


---np1---
[[2 3 3]
 [4 5 4]]
---np2---
[2 4 3 4]
----維度----
2
----形狀----
(2, 3)
----資料型別----
int64
int64


In [11]:
#建立填滿 0 或 1 的陣列

np1=np.zeros([3,2])#([列數,欄數],dtype)
np2=np.ones([3,2],int)
print(np1)
print(np2)

[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[1 1]
 [1 1]
 [1 1]]


In [23]:
#建立填滿特定數字的陣列

np1=np.full((4,5),9,int) #形狀,填充值,dtype=資料型態

np2=np.eye(5)#(row&col數,M=指定col,k=起始位置,dtype=資料型態)
np3=np.eye(5,M=6,k=1,dtype=int)

print(np1)
print("")
print(np2)
print("")
print(np3)

[[9 9 9 9 9]
 [9 9 9 9 9]
 [9 9 9 9 9]
 [9 9 9 9 9]]

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

[[0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]]


In [27]:
#建立填滿特定大小的陣列

#(起始值,停止值,生成數量,結尾,回傳模式,資料型態)
np1=np.linspace(1,10,4,1,0,dtype=int) 
np2=np.linspace(1,10,3,1,1,dtype=int)
np3=np.linspace(1,10,3,0,0,dtype=int) 

#(起始值,停止值,間距,資料型態)
np4=np.arange(10) #停止值

print(np1)
print(np2)#(陣列,間距)
print(np3)#生成數量為四個顯示3個
print(np4)



[ 1  4  7 10]
(array([ 1,  5, 10]), 4.5)
[1 4 7]
[0 1 2 3 4 5 6 7 8 9]


In [39]:
np2= np.array([[3,2,1],[1,6,4]])

print(np2[[0,1],[0,2]]) # =np2[0,0],np2[1,2]

print(np2[0,0])
print(np2[1,2])


[3 4]
3
4


In [40]:
np1=np.array([2,4,6])
np2=np.array([1,4,8])

print(np1+np2)
print(np1+3)
print(np1-np2)
print(np1*np2)
print(np1*2)
print(np1/np2)
print(np1/4)


[ 3  8 14]
[5 7 9]
[ 1  0 -2]
[ 2 16 48]
[ 4  8 12]
[2.   1.   0.75]
[0.5 1.  1.5]


In [54]:
#dot product 內積-1

data1=np.array([[4,5,6],[7,8,9],[10,11,12]]) 
data2=np.array([[3,1,2],[2,3,1],[1,2,3]])

print(np.dot(data1,data2))
print(data1.dot(data2))

[[28 31 31]
 [46 49 49]
 [64 67 67]]
[[28 31 31]
 [46 49 49]
 [64 67 67]]


In [79]:
#inner product 內積-2

data1=np.array([[1,2,3],[1,2,3],[1,0,3]]) #3*3
data2=np.array([[3,1,2],[2,3,1],[1,2,3]])#3*3
data3=np.array([[3,1,2],[2,3,1]]) #2*3

print(np.inner(data1,data2)) #2*3
print(">")
print(np.inner(data2,data1))

print(">")
print(data1)

print(">")
print(data3)
print(">")
print(np.inner(data1,data3))

[[11 11 14]
 [11 11 14]
 [ 9  5 10]]
>
[[11 11  9]
 [11 11  5]
 [14 14 10]]
>
[[1 2 3]
 [1 2 3]
 [1 0 3]]
>
[[3 1 2]
 [2 3 1]]
>
[[11 11]
 [11 11]
 [ 9  5]]


In [73]:
#outer product 外積

data1=np.array([[1,2,3],[1,2,3]]) #2*3 
data2=np.array([[1,1,2],[2,3,1],[1,2,3]]) #3*3

print(data1)
print("")
print(data2)
print("")

print(np.outer(data1,data2)) #6*9

[[1 2 3]
 [1 2 3]]

[[1 1 2]
 [2 3 1]
 [1 2 3]]

[[1 1 2 2 3 1 1 2 3]
 [2 2 4 4 6 2 2 4 6]
 [3 3 6 6 9 3 3 6 9]
 [1 1 2 2 3 1 1 2 3]
 [2 2 4 4 6 2 2 4 6]
 [3 3 6 6 9 3 3 6 9]]


In [75]:
data1=np.array([[7,2],[3,4]]) #2*2
data2=np.array([[3,1,2],[2,3,1]]) #2*3

print(np.outer(data1,data2))#4*6
print("")
print(np.outer(data2,data1))#6*4

[[21  7 14 14 21  7]
 [ 6  2  4  4  6  2]
 [ 9  3  6  6  9  3]
 [12  4  8  8 12  4]]

[[21  6  9 12]
 [ 7  2  3  4]
 [14  4  6  8]
 [14  4  6  8]
 [21  6  9 12]
 [ 7  2  3  4]]


In [80]:
np1=np.array([2,4,6])
np2=np.array([[1,2],[3,4]])

print(np1.sum())
print(np2.max())
print(np2.min())
print(np2.min(axis=0))#每欄最大值
print(np2.min(axis=1))#每列最大值
print(np.median(np1))
print(np.mean(np1))
print(np.std(np1))


12
4
1
[1 2]
[1 3]
4.0
4.0
1.632993161855452


In [92]:
np1=np.array([[2,4,6],[4,9,6]])
np2=np.array([[3,5],[4,7],[2,1]])

np2.sort(1)#排序層級 1 -> reverse=Ture(遞減)


print("np1")
print(np1)

print("重塑")
print(np1.reshape(3,2))

print("轉置")
print(np1.T)

print("解開")
print(np1.ravel())



np1
[[2 4 6]
 [4 9 6]]
重塑
[[2 4]
 [6 4]
 [9 6]]
轉置
[[2 4]
 [4 9]
 [6 6]]
解開
[2 4 6 4 9 6]


In [93]:
np1=np.array([[2,4,6],[4,9,6]])
np2=np.array([[3,5],[4,7],[2,1]])

print(np.append(np1,4))
print(np.append(np1,np2))
print(np.insert(np1,2,6)) #物件,位置,物件
print(np.delete(np1,[1]))

[2 4 6 4 9 6 4]
[2 4 6 4 9 6 3 5 4 7 2 1]
[2 4 6 6 4 9 6]
[2 6 4 9 6]


In [102]:
np1=np.array([[3,5],[4,7],[2,1]])

print("--V--")
np2,np3,np4=np.vsplit(np1,3)
print(np2)
print(np3)
print(np4)

print("--H---")
np5,np6=np.hsplit(np1,2)
print(np5)
print(np6)

--V--
[[3 5]]
[[4 7]]
[[2 1]]
--H---
[[3]
 [4]
 [2]]
[[5]
 [7]
 [1]]


In [122]:
list=map(int,input().split())

1 2 3 4
